name: Fecha

on:
  push:
    branches: [main]
  
  # schedule:
      # - cron: '0 0 * * *'

jobs:
  build:
    # runs-on: ubuntu-latest
    runs-on: self-hosted

    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          architecture: "x64"
        env:
          AGENT_TOOLSDIRECTORY: /opt/hostedtoolache
      
      # - name: Install pip
      #   run: pip install - requirements.txt

      - name: Run script
        run: python3 ./fecha_hora/fecha.py

      - name: Commit and Push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with: 
          commit_message: Update Fecha Hora
          commit_user_name: William Figueroa [Github Actions]
          commit_user_email: wrfigueroam@gmail.com
          commit_author: Dallas
