name: Metricas Entrenamiento 2

on:
  push:
    branches:
      - main

jobs:
  metricas_v2:
    runs-on: ubuntu-latest
    container: docker://ghcr.io/iterative/cml:0-dvc2-base1
    permissions:
      contents: write
    steps:
      - name: Verificar
        uses: actions/checkout@v3

      - name: Correr
        run: |
          pip install -r requirements.txt
          python train.py

          cat results.txt >> report.md
          echo '![](./graph.png "Confusion Matrix")' >> report.md
          cml comment create report.md
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
