name: Runner flask

on:
  push:
    branches:
      - main

jobs:
  prueba1:
    runs-on: self-hosted

    steps:
      - name: Verificar
        uses: actions/checkout@v3

      - name: Ejecutar
        run: |
          python app.py
  
